import type {Metadata} from 'next';
import {Archivo} from 'next/font/google';
import './globals.css';

const archivo = Archivo({
    variable: '--font-archivo',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'CodeLab | Login',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='pt-br'>
        <body
            className={`${archivo.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
